Hw 2
Axout/kts-android-09-2021 pull request #4
Opened 2021-09-26 15:28 UTC by Axout

2021-09-26 16:05 UTC, StefanSerkhir requested changes

2021-09-26 16:05 UTC, StefanSerkhir commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Странная зависимость, для чего?

2021-09-26 16:05 UTC, StefanSerkhir commented on app/build.gradle
> +        experimental = true
Для чего потребовалось experimental включать?

2021-09-26 16:05 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +    private lateinit var binding: FragmentLoginBinding
Советую использовать библиотеку https://github.com/androidbroadcast/ViewBindingPropertyDelegate

2021-09-26 16:05 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +                isValidEmail = Patterns.EMAIL_ADDRESS.matcher(text).matches()
Логику валидации необходимо вынести во ViewModel

2021-09-26 16:05 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +                if (text.length >= 8 && isValidEmail) {
Логику валидации необходимо вынести во ViewModel

2021-09-26 16:05 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +        with (binding.etPassword) {
Здесь использование with избыточно

2021-09-26 16:05 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +        with (binding.etEmailAddress) {
Здесь использование with избыточно

2021-09-26 16:51 UTC, Axout commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Да, legacy-support здесь лишнее. Видимо во время создания проекта пропустил галочку поддержки легаси.

2021-09-26 17:07 UTC, Axout commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Хотя нет, зацепил при копировании зависимостей из другого проекта.

2021-09-26 17:08 UTC, Axout commented on app/build.gradle
> +        experimental = true
Подключение viewBinding копировал из другого проекта, оттуда же и случайно скопировал включение плагина.
Согласен, здесь это тоже не нужно.

2021-09-26 17:21 UTC, Axout commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +    private lateinit var binding: FragmentLoginBinding
Да, с ней удобнее работать.

2021-09-28 21:31 UTC, StefanSerkhir approved these changes

2021-09-28 21:31 UTC, StefanSerkhir commented on app/src/main/res/layout/fragment_login.xml
> +            android:id="@+id/iv_valid"
Форматирование атрибутов в этом теге съехало на одну табуляцию вправо

2021-09-28 21:31 UTC, StefanSerkhir commented on app/src/main/res/layout/fragment_login.xml
> +    <EditText
Форматирование атрибутов в этом теге съехало на одну табуляцию вправо

2021-09-28 21:31 UTC, StefanSerkhir commented on app/src/main/res/layout/fragment_login.xml
> +    <EditText
можно применить автоформатирование (студия сама отформатирует код разметки как надо) 
Windows: Ctrl + Alt + L
Linux: Ctrl + Shift + Alt + L
macOS: Option + Command + L

2021-09-28 21:31 UTC, StefanSerkhir commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +            viewModel.validation(
лучше метод validation переименовать в validate, потому что validation - просто валидация, существительное,  а validate - валидировать, то есть глагол, отражающий то, что этот метод делает
такое соглашение хорошо описано в книге Чистый Код Роберта Мартина, целиком книжку читать может быть не быстро, есть статья с оч краткими выжимками из книги - https://habr.com/ru/post/485118/

2021-09-28 21:32 UTC, StefanSerkhir approved these changes

2021-09-29 04:47 UTC, Axout commented on app/src/main/res/layout/fragment_login.xml
> +    <EditText
Почему то у меня студия сама не форматирует код (у меня IntelliJ IDEA 2021.2.2).

2021-09-29 04:49 UTC, Axout commented on app/src/main/java/com/axout/kts_android_09_2021/LoginFragment.kt
> +            viewModel.validation(
Принято, спасибо!

2021-09-29 04:51 UTC, Axout commented on app/src/main/res/layout/fragment_login.xml
> +    <EditText
Точнее форматирует но не по госту, видимо это где-то настраивается... Я посмотрю.

2021-09-29 04:57 UTC, merged